name: Haskell CI

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v4
    - name: Install SystemDep
      run: |
        sudo apt install curl
    - name: Install Heskell
      run: |
        curl -sSL https://get.haskellstack.org/ -o heskellstack.sh
        sudo bash ./heskellstack.sh -d /usr/bin/"
        stack init
        stack update

    - name: Building
      run: |
        ls -l
        stack install
