name: Haskell CI

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v4
    - name: Install SystemDep
      run: |
        sudo apt install curl tar
    - name: Install Heskell
      run: |
        mkdir build
        cd build
        wget https://github.com/commercialhaskell/stack/releases/download/v3.5.1/stack-3.5.1-linux-aarch64.tar.gz
        tar xvf stack-3.5.1-linux-aarch64.tar.gz
        ls -l
        stack init
        stack update

    - name: Building
      run: |
        ls -l
        stack install
